# Generated by Django 4.1.1 on 2022-10-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('habitacion', '0001_initial'),
        ('promocion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHabitaciones', models.CharField(max_length=2, verbose_name='Cantiadad de Habitaciones')),
                ('numeroHuespedes', models.CharField(max_length=2, verbose_name='Numero de Huespedes')),
                ('valorReserva', models.CharField(max_length=7, verbose_name='Valor de Reserva')),
                ('metodoPago', models.CharField(max_length=45, verbose_name='Metodo de Pago')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha de Ingres')),
                ('fechaSalida', models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha de Salida')),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion', verbose_name='Habitacion')),
                ('Promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion', verbose_name='Promocion')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
