# Generated by Django 4.1.1 on 2022-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_remove_reserva_usuario_reserva_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
