# Generated by Django 4.1.1 on 2022-10-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promocion', '0001_initial'),
        ('reserva', '0006_reserva_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereserva',
            name='Promocion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion', verbose_name='Promocion'),
        ),
    ]
