# Generated by Django 4.1.1 on 2022-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_alter_detallereserva_promocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='detallereserva',
            name='fechaSalida',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaIngreso',
            field=models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check-In'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaSalida',
            field=models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check-Out'),
        ),
    ]
