# Generated by Django 4.1.1 on 2022-11-09 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_remove_detallereserva_fechaingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallereserva',
            old_name='Habitacion',
            new_name='habitacion',
        ),
        migrations.RenameField(
            model_name='detallereserva',
            old_name='Reserva',
            new_name='reserva',
        ),
        migrations.RemoveField(
            model_name='detallereserva',
            name='Promocion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidadHabitaciones',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='numeroHuespedes',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
    ]
