# Generated by Django 4.1.1 on 2022-11-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_alter_reserva_valorreserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='cantidad',
        ),
    ]
