# Generated by Django 4.1.1 on 2022-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoDocumento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
