# Generated by Django 4.1.1 on 2022-10-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_correo_usuario_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.CharField(max_length=45, unique=True, verbose_name='Número de Documento'),
        ),
    ]
