# Generated by Django 4.1.1 on 2022-10-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha de Creacion')),
                ('asunto', models.CharField(max_length=45, verbose_name='Asunto')),
                ('comentarioCliente', models.CharField(max_length=250, verbose_name='Comentario Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRespuesta', models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha de Respuesta')),
                ('respuestaPQRS', models.CharField(max_length=200, verbose_name='Respuesta PQRS')),
                ('quienRespondePQRS', models.CharField(max_length=45, verbose_name='Quien Responde PQRS')),
                ('canalRespuesta', models.CharField(max_length=45, verbose_name='Canal de Respuesta')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('PQRS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.pqrs', verbose_name='PQRS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Usuarios')),
            ],
        ),
    ]
