# Generated by Django 4.1.1 on 2022-10-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='respuestapqrs',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuarios'),
        ),
    ]
