# Generated by Django 4.1.1 on 2022-10-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_alter_pqrs_usuario_alter_respuestapqrs_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='respuestapqrs',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pqrs',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='nombres',
            field=models.CharField(blank=True, max_length=45, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='comentarioCliente',
            field=models.CharField(max_length=250, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='fechaCreacion',
            field=models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha'),
        ),
    ]
