# Generated by Django 4.1.1 on 2022-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_delete_respuestapqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
