# Generated by Django 4.1.1 on 2022-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_tipohabitacion_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='sede',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='sede',
            field=models.CharField(choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], default='estacion', max_length=8, verbose_name='Sede'),
        ),
    ]
