# Generated by Django 4.1.1 on 2022-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_remove_tipohabitacion_sede_habitacion_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='complementosTipoHabitacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complementos Tipo Habitacion'),
        ),
    ]
