# Generated by Django 4.1.1 on 2022-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0005_rename_tipohabitacion_habitacion_tipohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.CharField(max_length=4, verbose_name='Numero de Habitacion'),
        ),
    ]
