# Generated by Django 4.1.1 on 2022-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0006_alter_habitacion_numerohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.CharField(max_length=3, verbose_name='Numero de Habitacion'),
        ),
    ]
