# Generated by Django 4.1.1 on 2022-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0007_alter_habitacion_numerohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='complementosTipoHabitacion',
            field=models.CharField(choices=[('Ventilador', 'Ventilador'), ('Aire_Acondicionado', 'Aire Acondicionado')], default='Ventilador', max_length=20, verbose_name='Complementos Tipo Habitacion'),
        ),
    ]
