# Generated by Django 4.1.1 on 2022-10-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0008_alter_tipohabitacion_complementostipohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.CharField(max_length=4, verbose_name='Numero de Habitacion'),
        ),
    ]
