# Generated by Django 4.1.1 on 2022-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0009_alter_habitacion_numerohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='complementosTipoHabitacion',
            field=models.CharField(max_length=200, verbose_name='Complementos Tipo Habitacion'),
        ),
    ]
