# Generated by Django 4.1.1 on 2022-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0012_alter_tipohabitacion_complementostipohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.CharField(max_length=3, verbose_name='Numero de Habitacion'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='complementosTipoHabitacion',
            field=models.CharField(max_length=50, verbose_name='Complementos Tipo Habitacion'),
        ),
    ]
