# Generated by Django 4.1.1 on 2022-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0014_alter_habitacion_numerohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombreTipoHabitacion',
            field=models.CharField(choices=[('Sencilla ', 'Sencilla'), ('Doble', 'Doble'), ('Campestre', 'Campestre')], default='Sencilla ', max_length=10, verbose_name='Nombre Tipo de Habitacion'),
        ),
    ]
